// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/about.tsx";
import * as $1 from "./routes/api/pdf/_middleware.ts";
import * as $2 from "./routes/api/pdf/index.ts";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/resume.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Download.tsx";

const manifest = {
  routes: {
    "./routes/about.tsx": $0,
    "./routes/api/pdf/_middleware.ts": $1,
    "./routes/api/pdf/index.ts": $2,
    "./routes/index.tsx": $3,
    "./routes/resume.tsx": $4,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Download.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
